const path = require("path");
module.exports = {
  mode: "development",
  //entry: "./src/01Iterator/array/index.ts",
  //entry: "./src/02Strategy/index.ts",
  //entry: "./src/03Template/index.ts",
  //entry: "./src/04Adapter/index.ts",
  //entry: "./src/05Bridge/index.ts",
  //entry: "./src/06Decorator/index.ts",
  //entry: "./src/07Singleton/index.ts",
  //entry: "./src/08Flyweight/index.ts",
  //entry: "./src/09Composite/index.ts",
  //entry: "./src/10Factorymethod/index.ts",
  //entry: "./src/11Observer/index.ts",
  //entry: "./src/12Mediator/index.ts",
  //entry: "./src/13Memento/index.ts",
  //entry: "./src/14Proxy/index.ts",
  //entry: "./src/14Proxy/index.ts",
  //entry: "./src/14Proxy/index.ts",
  //entry: "./src/15ChainOfResponsibilty/index.ts",
  //entry: "./src/16Prototype/index.ts",
  //entry: "./src/17Facade/index.ts",
  //entry: "./src/18Builder/index.ts",
  entry: "./src/19Command/index.ts",
  //entry: "./src/20AbstractFactory/index.ts",
  //entry: "./src/21State/index.ts",
  //entry: "./src/22Interpreter/index.ts",
  //entry: "./src/23Visitor/index.ts",
  devtool: "inline-source-map",
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "dist"),
  },
};
